### ISSUE TITLE
MS2 spectrum is not matching the chromatogram

### ISSUE THREAD

**Issue by jiwony9** [mzmine/mzmine#1980] opened 2024-07-22 10:24 UTC
### Basic information

* My operating system and version: window
* My mzmine version: mzine4.1.0

### What happened

Hello, I want to export the mzmine processing data, but some problems arose.

https://ccms-ucsd.github.io/GNPSDocumentation/featurebasedmolecularnetworking-with-mzmine2/
I followed the method above, but I can't find some option (ex: chromatogram deconvolution)

For FBMN, ms2 data must be connected to the chromatogram created with chromatogram builder. 
However, this cannot be resolved.

The ms2 spectrum for m/z 388 exists as follows:
![image](https://github.com/user-attachments/assets/1bbf6b2b-12bd-46b4-9ea1-e18ba49db610)

![image](https://github.com/user-attachments/assets/53e96a54-ff52-4e6e-90cd-9cf0eebe342c)
However, when I create a chromatogram feature, ms/ms data does not connect. How do I connect(accept) ms2 data to the chromatogram feature?
plz help me

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the mzmine modules you used. 
* Please upload screenshots of any errors **and** your log/mzmine.log file.
* **Please upload a standalone mzmine project file (or a batch + raw files) that demonstrates the problem you are reporting.** You can use Google Drive, Dropbox, or a similar repository to upload the project.
* Issues opened without an example project are unlikely to be processed

**Comment by ansgarkorf** [comment] 2024-07-22 10:42
Hi,
you are a following a protocol for MZmine 2.53 which is not designed for mzmine 4.1.
For FBMN in mzmine 4.1, just use the LC-MS workflow of the mzwizard:
https://mzmine.github.io/mzmine_documentation/workflows/lcmsworkflow/lcms-workflow.html

**Comment by jiwony9** [comment] 2024-07-22 10:58
yes, I know, but the same issue is occured. Anyway, the problem can solved by assigning ms2 to the chromatogram. :(

**Comment by SteffenHeu** [comment] 2024-07-22 11:24
Hi, 
i think the issue is that the precursor mass in the MS2 is 388.0533 and the chromatogram/feature has an m/z of 388.0373, which is a massive difference. I think the scan m/zs may be recalibrated, but the set precursor mz is not. 

I can see that "masslynx" is in the filename, so i guess the data comes from a waters instrument. How did you convert the data? Please check if you followed this guide: https://mzmine.github.io/mzmine_documentation/data_conversion.html#waters

**Comment by jiwony9** [comment] 2024-07-22 11:37
yess, My data comes from a waters xevo-qtof and post process using followed guide (waters data connect).

I will try again with a wider ppm range!!

**Comment by jiwony9** [comment] 2024-07-22 11:38
thanks for kind apply @SteffenHeu @ansgarkorf :)

**Comment by SteffenHeu** [comment] 2024-07-22 11:41
you can set the tolerance in the resolving step at ms/ms scan pairing step

https://mzmine.github.io/mzmine_documentation/module_docs/featdet_resolver_local_minimum/local-minimum-resolver.html#msms-scan-pairing

https://mzmine.github.io/mzmine_documentation/module_docs/featdet_ms2_scan_pairing/ms2_scan_pairing.html#ms1-to-ms2-precursor-tolerance-mz

**Comment by jiwony9** [comment] 2024-07-22 11:41
![image](https://github.com/user-attachments/assets/5ff2a8b3-33cc-4000-9117-c07aebaee75c)

As you said, I set it to 0.05m/z or 20 ppm and it was resolved! thank you! @SteffenHeu

**Closed** 2024-07-25 09:57 UTC
